package cn.amy.apply.dao.mapper;

import cn.amy.apply.entity.HouseOrder;

public interface HouseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    int insert(HouseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    int insertSelective(HouseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    HouseOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseOrder record);
}