package cn.amy.apply.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HouseOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.house_info_id
     *
     * @mbggenerated
     */
    private String houseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.deposit
     *
     * @mbggenerated
     */
    private BigDecimal deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.coupons
     *
     * @mbggenerated
     */
    private String coupons;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.house_deposit
     *
     * @mbggenerated
     */
    private BigDecimal houseDeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.pay_price
     *
     * @mbggenerated
     */
    private BigDecimal payPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.stay_days
     *
     * @mbggenerated
     */
    private Integer stayDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.stay_id
     *
     * @mbggenerated
     */
    private String stayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.stay_phone
     *
     * @mbggenerated
     */
    private String stayPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.room_num
     *
     * @mbggenerated
     */
    private Integer roomNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.stay_num
     *
     * @mbggenerated
     */
    private Integer stayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.cust_id
     *
     * @mbggenerated
     */
    private String custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_order.work_id
     *
     * @mbggenerated
     */
    private String workId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.order_id
     *
     * @return the value of house_order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.order_id
     *
     * @param orderId the value for house_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.house_info_id
     *
     * @return the value of house_order.house_info_id
     *
     * @mbggenerated
     */
    public String getHouseInfoId() {
        return houseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.house_info_id
     *
     * @param houseInfoId the value for house_order.house_info_id
     *
     * @mbggenerated
     */
    public void setHouseInfoId(String houseInfoId) {
        this.houseInfoId = houseInfoId == null ? null : houseInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.order_num
     *
     * @return the value of house_order.order_num
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.order_num
     *
     * @param orderNum the value for house_order.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.total_price
     *
     * @return the value of house_order.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.total_price
     *
     * @param totalPrice the value for house_order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.deposit
     *
     * @return the value of house_order.deposit
     *
     * @mbggenerated
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.deposit
     *
     * @param deposit the value for house_order.deposit
     *
     * @mbggenerated
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.coupons
     *
     * @return the value of house_order.coupons
     *
     * @mbggenerated
     */
    public String getCoupons() {
        return coupons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.coupons
     *
     * @param coupons the value for house_order.coupons
     *
     * @mbggenerated
     */
    public void setCoupons(String coupons) {
        this.coupons = coupons == null ? null : coupons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.house_deposit
     *
     * @return the value of house_order.house_deposit
     *
     * @mbggenerated
     */
    public BigDecimal getHouseDeposit() {
        return houseDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.house_deposit
     *
     * @param houseDeposit the value for house_order.house_deposit
     *
     * @mbggenerated
     */
    public void setHouseDeposit(BigDecimal houseDeposit) {
        this.houseDeposit = houseDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.pay_price
     *
     * @return the value of house_order.pay_price
     *
     * @mbggenerated
     */
    public BigDecimal getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.pay_price
     *
     * @param payPrice the value for house_order.pay_price
     *
     * @mbggenerated
     */
    public void setPayPrice(BigDecimal payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.begin_date
     *
     * @return the value of house_order.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.begin_date
     *
     * @param beginDate the value for house_order.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.end_date
     *
     * @return the value of house_order.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.end_date
     *
     * @param endDate the value for house_order.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.stay_days
     *
     * @return the value of house_order.stay_days
     *
     * @mbggenerated
     */
    public Integer getStayDays() {
        return stayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.stay_days
     *
     * @param stayDays the value for house_order.stay_days
     *
     * @mbggenerated
     */
    public void setStayDays(Integer stayDays) {
        this.stayDays = stayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.stay_id
     *
     * @return the value of house_order.stay_id
     *
     * @mbggenerated
     */
    public String getStayId() {
        return stayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.stay_id
     *
     * @param stayId the value for house_order.stay_id
     *
     * @mbggenerated
     */
    public void setStayId(String stayId) {
        this.stayId = stayId == null ? null : stayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.stay_phone
     *
     * @return the value of house_order.stay_phone
     *
     * @mbggenerated
     */
    public String getStayPhone() {
        return stayPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.stay_phone
     *
     * @param stayPhone the value for house_order.stay_phone
     *
     * @mbggenerated
     */
    public void setStayPhone(String stayPhone) {
        this.stayPhone = stayPhone == null ? null : stayPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.room_num
     *
     * @return the value of house_order.room_num
     *
     * @mbggenerated
     */
    public Integer getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.room_num
     *
     * @param roomNum the value for house_order.room_num
     *
     * @mbggenerated
     */
    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.stay_num
     *
     * @return the value of house_order.stay_num
     *
     * @mbggenerated
     */
    public Integer getStayNum() {
        return stayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.stay_num
     *
     * @param stayNum the value for house_order.stay_num
     *
     * @mbggenerated
     */
    public void setStayNum(Integer stayNum) {
        this.stayNum = stayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.order_status
     *
     * @return the value of house_order.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.order_status
     *
     * @param orderStatus the value for house_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.pay_status
     *
     * @return the value of house_order.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.pay_status
     *
     * @param payStatus the value for house_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.create_time
     *
     * @return the value of house_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.create_time
     *
     * @param createTime the value for house_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.pay_time
     *
     * @return the value of house_order.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.pay_time
     *
     * @param payTime the value for house_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.cust_id
     *
     * @return the value of house_order.cust_id
     *
     * @mbggenerated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.cust_id
     *
     * @param custId the value for house_order.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_order.work_id
     *
     * @return the value of house_order.work_id
     *
     * @mbggenerated
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_order.work_id
     *
     * @param workId the value for house_order.work_id
     *
     * @mbggenerated
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }
}