package cn.amy.user.dao.mapper;

import cn.amy.user.entity.Coupons;

public interface CouponsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    int insert(Coupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    int insertSelective(Coupons record);
}