package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HotCity;

public interface HotCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String hotCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    int insert(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    int insertSelective(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    HotCity selectByPrimaryKey(String hotCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotCity record);
}