package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HouseStatus;

public interface HouseStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    int insert(HouseStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    int insertSelective(HouseStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    HouseStatus selectByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseStatus record);
}