package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HouseImage;

public interface HouseImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    int insert(HouseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    int insertSelective(HouseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    HouseImage selectByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseImage record);
}