package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HouseAddress;

public interface HouseAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String houseAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    int insert(HouseAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    int insertSelective(HouseAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    HouseAddress selectByPrimaryKey(String houseAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseAddress record);
}