package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HouseholdAppliances;

public interface HouseholdAppliancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String facilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    int insert(HouseholdAppliances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    int insertSelective(HouseholdAppliances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    HouseholdAppliances selectByPrimaryKey(String facilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseholdAppliances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_appliances
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseholdAppliances record);
}