package cn.amy.product.dao.mapper;

import cn.amy.product.entity.HouseInfo;

public interface HouseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String houseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    int insert(HouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    int insertSelective(HouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    HouseInfo selectByPrimaryKey(String houseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseInfo record);
}