package cn.amy.product.dao.mapper;

import cn.amy.product.entity.PriceCalendar;

public interface PriceCalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    int insert(PriceCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    int insertSelective(PriceCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    PriceCalendar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PriceCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PriceCalendar record);
}