package cn.amy.user.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Coupons {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.effec_time
     *
     * @mbggenerated
     */
    private Integer effecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupons.failure_time
     *
     * @mbggenerated
     */
    private Date failureTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.id
     *
     * @return the value of coupons.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.id
     *
     * @param id the value for coupons.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.name
     *
     * @return the value of coupons.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.name
     *
     * @param name the value for coupons.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.user_id
     *
     * @return the value of coupons.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.user_id
     *
     * @param userId the value for coupons.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.amount
     *
     * @return the value of coupons.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.amount
     *
     * @param amount the value for coupons.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.status
     *
     * @return the value of coupons.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.status
     *
     * @param status the value for coupons.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.create_user
     *
     * @return the value of coupons.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.create_user
     *
     * @param createUser the value for coupons.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.create_time
     *
     * @return the value of coupons.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.create_time
     *
     * @param createTime the value for coupons.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.effec_time
     *
     * @return the value of coupons.effec_time
     *
     * @mbggenerated
     */
    public Integer getEffecTime() {
        return effecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.effec_time
     *
     * @param effecTime the value for coupons.effec_time
     *
     * @mbggenerated
     */
    public void setEffecTime(Integer effecTime) {
        this.effecTime = effecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupons.failure_time
     *
     * @return the value of coupons.failure_time
     *
     * @mbggenerated
     */
    public Date getFailureTime() {
        return failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupons.failure_time
     *
     * @param failureTime the value for coupons.failure_time
     *
     * @mbggenerated
     */
    public void setFailureTime(Date failureTime) {
        this.failureTime = failureTime;
    }
}