package cn.amy.user.entity;

import java.util.Date;

public class CustPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.landlord_id
     *
     * @mbggenerated
     */
    private String landlordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ID_FROM_DATE
     *
     * @mbggenerated
     */
    private Date idFromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ID_THRU_DATE
     *
     * @mbggenerated
     */
    private Date idThruDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.FRONT_CONTENT_ID
     *
     * @mbggenerated
     */
    private String frontContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.BACK_CONTENT_ID
     *
     * @mbggenerated
     */
    private String backContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.IDENTIFICATION_ID
     *
     * @mbggenerated
     */
    private Long identificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.DISTRICT
     *
     * @mbggenerated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.EDUCATION_ENUM
     *
     * @mbggenerated
     */
    private String educationEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.DEGREE_ENUM
     *
     * @mbggenerated
     */
    private String degreeEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.head_url
     *
     * @mbggenerated
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.MARRAGE_ENUM
     *
     * @mbggenerated
     */
    private String marrageEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.OCCUPATION_ENUM
     *
     * @mbggenerated
     */
    private String occupationEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.TITLE_ENUM
     *
     * @mbggenerated
     */
    private String titleEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.PTITLE_ENUM
     *
     * @mbggenerated
     */
    private String ptitleEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.WORKING_UNIT
     *
     * @mbggenerated
     */
    private String workingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.INDUSTRY_ENUM
     *
     * @mbggenerated
     */
    private String industryEnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ACCOUNT_NO
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.ACCOUNT_MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String accountMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.LAST_MODIFIED_SEQ
     *
     * @mbggenerated
     */
    private Long lastModifiedSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.QQ_NO
     *
     * @mbggenerated
     */
    private String qqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST_PERSON.WEECHAT_NO
     *
     * @mbggenerated
     */
    private String weechatNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.landlord_id
     *
     * @return the value of CUST_PERSON.landlord_id
     *
     * @mbggenerated
     */
    public String getLandlordId() {
        return landlordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.landlord_id
     *
     * @param landlordId the value for CUST_PERSON.landlord_id
     *
     * @mbggenerated
     */
    public void setLandlordId(String landlordId) {
        this.landlordId = landlordId == null ? null : landlordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.user_id
     *
     * @return the value of CUST_PERSON.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.user_id
     *
     * @param userId the value for CUST_PERSON.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.NAME
     *
     * @return the value of CUST_PERSON.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.NAME
     *
     * @param name the value for CUST_PERSON.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.alias
     *
     * @return the value of CUST_PERSON.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.alias
     *
     * @param alias the value for CUST_PERSON.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.english_name
     *
     * @return the value of CUST_PERSON.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.english_name
     *
     * @param englishName the value for CUST_PERSON.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.MOBILE_PHONE
     *
     * @return the value of CUST_PERSON.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.MOBILE_PHONE
     *
     * @param mobilePhone the value for CUST_PERSON.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ID_NO
     *
     * @return the value of CUST_PERSON.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ID_NO
     *
     * @param idNo the value for CUST_PERSON.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ID_FROM_DATE
     *
     * @return the value of CUST_PERSON.ID_FROM_DATE
     *
     * @mbggenerated
     */
    public Date getIdFromDate() {
        return idFromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ID_FROM_DATE
     *
     * @param idFromDate the value for CUST_PERSON.ID_FROM_DATE
     *
     * @mbggenerated
     */
    public void setIdFromDate(Date idFromDate) {
        this.idFromDate = idFromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ID_THRU_DATE
     *
     * @return the value of CUST_PERSON.ID_THRU_DATE
     *
     * @mbggenerated
     */
    public Date getIdThruDate() {
        return idThruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ID_THRU_DATE
     *
     * @param idThruDate the value for CUST_PERSON.ID_THRU_DATE
     *
     * @mbggenerated
     */
    public void setIdThruDate(Date idThruDate) {
        this.idThruDate = idThruDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.FRONT_CONTENT_ID
     *
     * @return the value of CUST_PERSON.FRONT_CONTENT_ID
     *
     * @mbggenerated
     */
    public String getFrontContentId() {
        return frontContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.FRONT_CONTENT_ID
     *
     * @param frontContentId the value for CUST_PERSON.FRONT_CONTENT_ID
     *
     * @mbggenerated
     */
    public void setFrontContentId(String frontContentId) {
        this.frontContentId = frontContentId == null ? null : frontContentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.BACK_CONTENT_ID
     *
     * @return the value of CUST_PERSON.BACK_CONTENT_ID
     *
     * @mbggenerated
     */
    public String getBackContentId() {
        return backContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.BACK_CONTENT_ID
     *
     * @param backContentId the value for CUST_PERSON.BACK_CONTENT_ID
     *
     * @mbggenerated
     */
    public void setBackContentId(String backContentId) {
        this.backContentId = backContentId == null ? null : backContentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.IDENTIFICATION_ID
     *
     * @return the value of CUST_PERSON.IDENTIFICATION_ID
     *
     * @mbggenerated
     */
    public Long getIdentificationId() {
        return identificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.IDENTIFICATION_ID
     *
     * @param identificationId the value for CUST_PERSON.IDENTIFICATION_ID
     *
     * @mbggenerated
     */
    public void setIdentificationId(Long identificationId) {
        this.identificationId = identificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.PROVINCE
     *
     * @return the value of CUST_PERSON.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.PROVINCE
     *
     * @param province the value for CUST_PERSON.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.CITY
     *
     * @return the value of CUST_PERSON.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.CITY
     *
     * @param city the value for CUST_PERSON.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.DISTRICT
     *
     * @return the value of CUST_PERSON.DISTRICT
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.DISTRICT
     *
     * @param district the value for CUST_PERSON.DISTRICT
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ADDRESS
     *
     * @return the value of CUST_PERSON.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ADDRESS
     *
     * @param address the value for CUST_PERSON.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.EDUCATION_ENUM
     *
     * @return the value of CUST_PERSON.EDUCATION_ENUM
     *
     * @mbggenerated
     */
    public String getEducationEnum() {
        return educationEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.EDUCATION_ENUM
     *
     * @param educationEnum the value for CUST_PERSON.EDUCATION_ENUM
     *
     * @mbggenerated
     */
    public void setEducationEnum(String educationEnum) {
        this.educationEnum = educationEnum == null ? null : educationEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.DEGREE_ENUM
     *
     * @return the value of CUST_PERSON.DEGREE_ENUM
     *
     * @mbggenerated
     */
    public String getDegreeEnum() {
        return degreeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.DEGREE_ENUM
     *
     * @param degreeEnum the value for CUST_PERSON.DEGREE_ENUM
     *
     * @mbggenerated
     */
    public void setDegreeEnum(String degreeEnum) {
        this.degreeEnum = degreeEnum == null ? null : degreeEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.introduce
     *
     * @return the value of CUST_PERSON.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.introduce
     *
     * @param introduce the value for CUST_PERSON.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.type
     *
     * @return the value of CUST_PERSON.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.type
     *
     * @param type the value for CUST_PERSON.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.head_url
     *
     * @return the value of CUST_PERSON.head_url
     *
     * @mbggenerated
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.head_url
     *
     * @param headUrl the value for CUST_PERSON.head_url
     *
     * @mbggenerated
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.MARRAGE_ENUM
     *
     * @return the value of CUST_PERSON.MARRAGE_ENUM
     *
     * @mbggenerated
     */
    public String getMarrageEnum() {
        return marrageEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.MARRAGE_ENUM
     *
     * @param marrageEnum the value for CUST_PERSON.MARRAGE_ENUM
     *
     * @mbggenerated
     */
    public void setMarrageEnum(String marrageEnum) {
        this.marrageEnum = marrageEnum == null ? null : marrageEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.OCCUPATION_ENUM
     *
     * @return the value of CUST_PERSON.OCCUPATION_ENUM
     *
     * @mbggenerated
     */
    public String getOccupationEnum() {
        return occupationEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.OCCUPATION_ENUM
     *
     * @param occupationEnum the value for CUST_PERSON.OCCUPATION_ENUM
     *
     * @mbggenerated
     */
    public void setOccupationEnum(String occupationEnum) {
        this.occupationEnum = occupationEnum == null ? null : occupationEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.TITLE_ENUM
     *
     * @return the value of CUST_PERSON.TITLE_ENUM
     *
     * @mbggenerated
     */
    public String getTitleEnum() {
        return titleEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.TITLE_ENUM
     *
     * @param titleEnum the value for CUST_PERSON.TITLE_ENUM
     *
     * @mbggenerated
     */
    public void setTitleEnum(String titleEnum) {
        this.titleEnum = titleEnum == null ? null : titleEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.PTITLE_ENUM
     *
     * @return the value of CUST_PERSON.PTITLE_ENUM
     *
     * @mbggenerated
     */
    public String getPtitleEnum() {
        return ptitleEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.PTITLE_ENUM
     *
     * @param ptitleEnum the value for CUST_PERSON.PTITLE_ENUM
     *
     * @mbggenerated
     */
    public void setPtitleEnum(String ptitleEnum) {
        this.ptitleEnum = ptitleEnum == null ? null : ptitleEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.WORKING_UNIT
     *
     * @return the value of CUST_PERSON.WORKING_UNIT
     *
     * @mbggenerated
     */
    public String getWorkingUnit() {
        return workingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.WORKING_UNIT
     *
     * @param workingUnit the value for CUST_PERSON.WORKING_UNIT
     *
     * @mbggenerated
     */
    public void setWorkingUnit(String workingUnit) {
        this.workingUnit = workingUnit == null ? null : workingUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.INDUSTRY_ENUM
     *
     * @return the value of CUST_PERSON.INDUSTRY_ENUM
     *
     * @mbggenerated
     */
    public String getIndustryEnum() {
        return industryEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.INDUSTRY_ENUM
     *
     * @param industryEnum the value for CUST_PERSON.INDUSTRY_ENUM
     *
     * @mbggenerated
     */
    public void setIndustryEnum(String industryEnum) {
        this.industryEnum = industryEnum == null ? null : industryEnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.EMAIL
     *
     * @return the value of CUST_PERSON.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.EMAIL
     *
     * @param email the value for CUST_PERSON.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ACCOUNT_NO
     *
     * @return the value of CUST_PERSON.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ACCOUNT_NO
     *
     * @param accountNo the value for CUST_PERSON.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.ACCOUNT_MOBILE_PHONE
     *
     * @return the value of CUST_PERSON.ACCOUNT_MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getAccountMobilePhone() {
        return accountMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.ACCOUNT_MOBILE_PHONE
     *
     * @param accountMobilePhone the value for CUST_PERSON.ACCOUNT_MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setAccountMobilePhone(String accountMobilePhone) {
        this.accountMobilePhone = accountMobilePhone == null ? null : accountMobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.CREATE_BY
     *
     * @return the value of CUST_PERSON.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.CREATE_BY
     *
     * @param createBy the value for CUST_PERSON.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.CREATE_TIME
     *
     * @return the value of CUST_PERSON.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.CREATE_TIME
     *
     * @param createTime the value for CUST_PERSON.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.LAST_MODIFIED_BY
     *
     * @return the value of CUST_PERSON.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for CUST_PERSON.LAST_MODIFIED_BY
     *
     * @mbggenerated
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.LAST_MODIFIED_TIME
     *
     * @return the value of CUST_PERSON.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for CUST_PERSON.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.LAST_MODIFIED_SEQ
     *
     * @return the value of CUST_PERSON.LAST_MODIFIED_SEQ
     *
     * @mbggenerated
     */
    public Long getLastModifiedSeq() {
        return lastModifiedSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.LAST_MODIFIED_SEQ
     *
     * @param lastModifiedSeq the value for CUST_PERSON.LAST_MODIFIED_SEQ
     *
     * @mbggenerated
     */
    public void setLastModifiedSeq(Long lastModifiedSeq) {
        this.lastModifiedSeq = lastModifiedSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.QQ_NO
     *
     * @return the value of CUST_PERSON.QQ_NO
     *
     * @mbggenerated
     */
    public String getQqNo() {
        return qqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.QQ_NO
     *
     * @param qqNo the value for CUST_PERSON.QQ_NO
     *
     * @mbggenerated
     */
    public void setQqNo(String qqNo) {
        this.qqNo = qqNo == null ? null : qqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST_PERSON.WEECHAT_NO
     *
     * @return the value of CUST_PERSON.WEECHAT_NO
     *
     * @mbggenerated
     */
    public String getWeechatNo() {
        return weechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST_PERSON.WEECHAT_NO
     *
     * @param weechatNo the value for CUST_PERSON.WEECHAT_NO
     *
     * @mbggenerated
     */
    public void setWeechatNo(String weechatNo) {
        this.weechatNo = weechatNo == null ? null : weechatNo.trim();
    }

	@Override
	public String toString() {
		return "CustPerson [landlordId=" + landlordId + ", userId=" + userId + ", name=" + name + ", alias=" + alias
				+ ", englishName=" + englishName + ", mobilePhone=" + mobilePhone + ", idNo=" + idNo + ", idFromDate="
				+ idFromDate + ", idThruDate=" + idThruDate + ", frontContentId=" + frontContentId + ", backContentId="
				+ backContentId + ", identificationId=" + identificationId + ", province=" + province + ", city=" + city
				+ ", district=" + district + ", address=" + address + ", educationEnum=" + educationEnum
				+ ", degreeEnum=" + degreeEnum + ", introduce=" + introduce + ", type=" + type + ", headUrl=" + headUrl
				+ ", marrageEnum=" + marrageEnum + ", occupationEnum=" + occupationEnum + ", titleEnum=" + titleEnum
				+ ", ptitleEnum=" + ptitleEnum + ", workingUnit=" + workingUnit + ", industryEnum=" + industryEnum
				+ ", email=" + email + ", accountNo=" + accountNo + ", accountMobilePhone=" + accountMobilePhone
				+ ", createBy=" + createBy + ", createTime=" + createTime + ", lastModifiedBy=" + lastModifiedBy
				+ ", lastModifiedTime=" + lastModifiedTime + ", lastModifiedSeq=" + lastModifiedSeq + ", qqNo=" + qqNo
				+ ", weechatNo=" + weechatNo + "]";
	}
    
    
    
    
}