package cn.amy.user.entity;

import java.io.Serializable;

public class User implements Serializable{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.orders_id
	 * @mbggenerated
	 */
	private Integer ordersId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.tell_code
	 * @mbggenerated
	 */
	private String tellCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sms_code
	 * @mbggenerated
	 */
	private String smsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.invite_code
	 * @mbggenerated
	 */
	private String inviteCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.com_info
	 * @mbggenerated
	 */
	private String comInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.coupons_id
	 * @mbggenerated
	 */
	private Integer couponsId;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.orders_id
	 * @return  the value of user.orders_id
	 * @mbggenerated
	 */
	public Integer getOrdersId() {
		return ordersId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.orders_id
	 * @param ordersId  the value for user.orders_id
	 * @mbggenerated
	 */
	public void setOrdersId(Integer ordersId) {
		this.ordersId = ordersId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.tell_code
	 * @return  the value of user.tell_code
	 * @mbggenerated
	 */
	public String getTellCode() {
		return tellCode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.tell_code
	 * @param tellCode  the value for user.tell_code
	 * @mbggenerated
	 */
	public void setTellCode(String tellCode) {
		this.tellCode = tellCode == null ? null : tellCode.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sms_code
	 * @return  the value of user.sms_code
	 * @mbggenerated
	 */
	public String getSmsCode() {
		return smsCode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sms_code
	 * @param smsCode  the value for user.sms_code
	 * @mbggenerated
	 */
	public void setSmsCode(String smsCode) {
		this.smsCode = smsCode == null ? null : smsCode.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.invite_code
	 * @return  the value of user.invite_code
	 * @mbggenerated
	 */
	public String getInviteCode() {
		return inviteCode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.invite_code
	 * @param inviteCode  the value for user.invite_code
	 * @mbggenerated
	 */
	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode == null ? null : inviteCode.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.com_info
	 * @return  the value of user.com_info
	 * @mbggenerated
	 */
	public String getComInfo() {
		return comInfo;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.com_info
	 * @param comInfo  the value for user.com_info
	 * @mbggenerated
	 */
	public void setComInfo(String comInfo) {
		this.comInfo = comInfo == null ? null : comInfo.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.coupons_id
	 * @return  the value of user.coupons_id
	 * @mbggenerated
	 */
	public Integer getCouponsId() {
		return couponsId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.coupons_id
	 * @param couponsId  the value for user.coupons_id
	 * @mbggenerated
	 */
	public void setCouponsId(Integer couponsId) {
		this.couponsId = couponsId;
	}

	
}
