package cn.amy.product.entity;

public class HotActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_activity.hot_activity_id
     *
     * @mbggenerated
     */
    private String hotActivityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_activity.hot_activity_name
     *
     * @mbggenerated
     */
    private String hotActivityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_activity.hot_activity_des
     *
     * @mbggenerated
     */
    private String hotActivityDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_activity.hot_activity_image_url
     *
     * @mbggenerated
     */
    private String hotActivityImageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_activity.hot_activity_id
     *
     * @return the value of hot_activity.hot_activity_id
     *
     * @mbggenerated
     */
    public String getHotActivityId() {
        return hotActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_activity.hot_activity_id
     *
     * @param hotActivityId the value for hot_activity.hot_activity_id
     *
     * @mbggenerated
     */
    public void setHotActivityId(String hotActivityId) {
        this.hotActivityId = hotActivityId == null ? null : hotActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_activity.hot_activity_name
     *
     * @return the value of hot_activity.hot_activity_name
     *
     * @mbggenerated
     */
    public String getHotActivityName() {
        return hotActivityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_activity.hot_activity_name
     *
     * @param hotActivityName the value for hot_activity.hot_activity_name
     *
     * @mbggenerated
     */
    public void setHotActivityName(String hotActivityName) {
        this.hotActivityName = hotActivityName == null ? null : hotActivityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_activity.hot_activity_des
     *
     * @return the value of hot_activity.hot_activity_des
     *
     * @mbggenerated
     */
    public String getHotActivityDes() {
        return hotActivityDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_activity.hot_activity_des
     *
     * @param hotActivityDes the value for hot_activity.hot_activity_des
     *
     * @mbggenerated
     */
    public void setHotActivityDes(String hotActivityDes) {
        this.hotActivityDes = hotActivityDes == null ? null : hotActivityDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_activity.hot_activity_image_url
     *
     * @return the value of hot_activity.hot_activity_image_url
     *
     * @mbggenerated
     */
    public String getHotActivityImageUrl() {
        return hotActivityImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_activity.hot_activity_image_url
     *
     * @param hotActivityImageUrl the value for hot_activity.hot_activity_image_url
     *
     * @mbggenerated
     */
    public void setHotActivityImageUrl(String hotActivityImageUrl) {
        this.hotActivityImageUrl = hotActivityImageUrl == null ? null : hotActivityImageUrl.trim();
    }
}