package cn.amy.product.entity;

public class HotCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.hot_city_id
     *
     * @mbggenerated
     */
    private String hotCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.province_id
     *
     * @mbggenerated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.address_image_url
     *
     * @mbggenerated
     */
    private String addressImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.province_spell
     *
     * @mbggenerated
     */
    private String provinceSpell;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.hot_city_id
     *
     * @return the value of hot_city.hot_city_id
     *
     * @mbggenerated
     */
    public String getHotCityId() {
        return hotCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.hot_city_id
     *
     * @param hotCityId the value for hot_city.hot_city_id
     *
     * @mbggenerated
     */
    public void setHotCityId(String hotCityId) {
        this.hotCityId = hotCityId == null ? null : hotCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.province_id
     *
     * @return the value of hot_city.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.province_id
     *
     * @param provinceId the value for hot_city.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.province_name
     *
     * @return the value of hot_city.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.province_name
     *
     * @param provinceName the value for hot_city.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.address_image_url
     *
     * @return the value of hot_city.address_image_url
     *
     * @mbggenerated
     */
    public String getAddressImageUrl() {
        return addressImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.address_image_url
     *
     * @param addressImageUrl the value for hot_city.address_image_url
     *
     * @mbggenerated
     */
    public void setAddressImageUrl(String addressImageUrl) {
        this.addressImageUrl = addressImageUrl == null ? null : addressImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.province_spell
     *
     * @return the value of hot_city.province_spell
     *
     * @mbggenerated
     */
    public String getProvinceSpell() {
        return provinceSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.province_spell
     *
     * @param provinceSpell the value for hot_city.province_spell
     *
     * @mbggenerated
     */
    public void setProvinceSpell(String provinceSpell) {
        this.provinceSpell = provinceSpell == null ? null : provinceSpell.trim();
    }
}