package cn.amy.product.entity;

public class HouseAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_address.house_address_id
     *
     * @mbggenerated
     */
    private String houseAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_address.province_id
     *
     * @mbggenerated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_address.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_address.address_image_url
     *
     * @mbggenerated
     */
    private String addressImageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_address.house_address_id
     *
     * @return the value of house_address.house_address_id
     *
     * @mbggenerated
     */
    public String getHouseAddressId() {
        return houseAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_address.house_address_id
     *
     * @param houseAddressId the value for house_address.house_address_id
     *
     * @mbggenerated
     */
    public void setHouseAddressId(String houseAddressId) {
        this.houseAddressId = houseAddressId == null ? null : houseAddressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_address.province_id
     *
     * @return the value of house_address.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_address.province_id
     *
     * @param provinceId the value for house_address.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_address.province_name
     *
     * @return the value of house_address.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_address.province_name
     *
     * @param provinceName the value for house_address.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_address.address_image_url
     *
     * @return the value of house_address.address_image_url
     *
     * @mbggenerated
     */
    public String getAddressImageUrl() {
        return addressImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_address.address_image_url
     *
     * @param addressImageUrl the value for house_address.address_image_url
     *
     * @mbggenerated
     */
    public void setAddressImageUrl(String addressImageUrl) {
        this.addressImageUrl = addressImageUrl == null ? null : addressImageUrl.trim();
    }
}