package cn.amy.product.entity;

public class HouseholdAppliances {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_appliances.facility_id
     *
     * @mbggenerated
     */
    private String facilityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_appliances.house_info_id
     *
     * @mbggenerated
     */
    private String houseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_appliances.facility_kind
     *
     * @mbggenerated
     */
    private String facilityKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_appliances.facility_sort
     *
     * @mbggenerated
     */
    private Integer facilitySort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_appliances.facility_icon_url
     *
     * @mbggenerated
     */
    private String facilityIconUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_appliances.facility_id
     *
     * @return the value of household_appliances.facility_id
     *
     * @mbggenerated
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_appliances.facility_id
     *
     * @param facilityId the value for household_appliances.facility_id
     *
     * @mbggenerated
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId == null ? null : facilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_appliances.house_info_id
     *
     * @return the value of household_appliances.house_info_id
     *
     * @mbggenerated
     */
    public String getHouseInfoId() {
        return houseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_appliances.house_info_id
     *
     * @param houseInfoId the value for household_appliances.house_info_id
     *
     * @mbggenerated
     */
    public void setHouseInfoId(String houseInfoId) {
        this.houseInfoId = houseInfoId == null ? null : houseInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_appliances.facility_kind
     *
     * @return the value of household_appliances.facility_kind
     *
     * @mbggenerated
     */
    public String getFacilityKind() {
        return facilityKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_appliances.facility_kind
     *
     * @param facilityKind the value for household_appliances.facility_kind
     *
     * @mbggenerated
     */
    public void setFacilityKind(String facilityKind) {
        this.facilityKind = facilityKind == null ? null : facilityKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_appliances.facility_sort
     *
     * @return the value of household_appliances.facility_sort
     *
     * @mbggenerated
     */
    public Integer getFacilitySort() {
        return facilitySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_appliances.facility_sort
     *
     * @param facilitySort the value for household_appliances.facility_sort
     *
     * @mbggenerated
     */
    public void setFacilitySort(Integer facilitySort) {
        this.facilitySort = facilitySort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_appliances.facility_icon_url
     *
     * @return the value of household_appliances.facility_icon_url
     *
     * @mbggenerated
     */
    public String getFacilityIconUrl() {
        return facilityIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_appliances.facility_icon_url
     *
     * @param facilityIconUrl the value for household_appliances.facility_icon_url
     *
     * @mbggenerated
     */
    public void setFacilityIconUrl(String facilityIconUrl) {
        this.facilityIconUrl = facilityIconUrl == null ? null : facilityIconUrl.trim();
    }
}