package cn.amy.product.entity;

import java.util.Date;

public class HouseImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.image_id
     *
     * @mbggenerated
     */
    private String imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.house_info_id
     *
     * @mbggenerated
     */
    private String houseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.house_image_url
     *
     * @mbggenerated
     */
    private String houseImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.house_image_no
     *
     * @mbggenerated
     */
    private Integer houseImageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_image.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.image_id
     *
     * @return the value of house_image.image_id
     *
     * @mbggenerated
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.image_id
     *
     * @param imageId the value for house_image.image_id
     *
     * @mbggenerated
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.house_info_id
     *
     * @return the value of house_image.house_info_id
     *
     * @mbggenerated
     */
    public String getHouseInfoId() {
        return houseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.house_info_id
     *
     * @param houseInfoId the value for house_image.house_info_id
     *
     * @mbggenerated
     */
    public void setHouseInfoId(String houseInfoId) {
        this.houseInfoId = houseInfoId == null ? null : houseInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.house_image_url
     *
     * @return the value of house_image.house_image_url
     *
     * @mbggenerated
     */
    public String getHouseImageUrl() {
        return houseImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.house_image_url
     *
     * @param houseImageUrl the value for house_image.house_image_url
     *
     * @mbggenerated
     */
    public void setHouseImageUrl(String houseImageUrl) {
        this.houseImageUrl = houseImageUrl == null ? null : houseImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.house_image_no
     *
     * @return the value of house_image.house_image_no
     *
     * @mbggenerated
     */
    public Integer getHouseImageNo() {
        return houseImageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.house_image_no
     *
     * @param houseImageNo the value for house_image.house_image_no
     *
     * @mbggenerated
     */
    public void setHouseImageNo(Integer houseImageNo) {
        this.houseImageNo = houseImageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.create_user
     *
     * @return the value of house_image.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.create_user
     *
     * @param createUser the value for house_image.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.create_time
     *
     * @return the value of house_image.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.create_time
     *
     * @param createTime the value for house_image.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.modify_user
     *
     * @return the value of house_image.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.modify_user
     *
     * @param modifyUser the value for house_image.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_image.modify_time
     *
     * @return the value of house_image.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_image.modify_time
     *
     * @param modifyTime the value for house_image.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}