package cn.amy.product.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HouseInfo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.house_info_id
	 * @mbggenerated
	 */
	private String houseInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.landlord_id
	 * @mbggenerated
	 */
	private String landlordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.province
	 * @mbggenerated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.city
	 * @mbggenerated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.price
	 * @mbggenerated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.district
	 * @mbggenerated
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.longitude
	 * @mbggenerated
	 */
	private BigDecimal longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.latitude
	 * @mbggenerated
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.signature_url
	 * @mbggenerated
	 */
	private String signatureUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.img_url
	 * @mbggenerated
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.predict_sum
	 * @mbggenerated
	 */
	private Integer predictSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.is_hot_house
	 * @mbggenerated
	 */
	private String isHotHouse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.creater
	 * @mbggenerated
	 */
	private String creater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.modify_user
	 * @mbggenerated
	 */
	private String modifyUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.modify_time
	 * @mbggenerated
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.house_type
	 * @mbggenerated
	 */
	private String houseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.house_describe
	 * @mbggenerated
	 */
	private String houseDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.grade
	 * @mbggenerated
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.room_sum
	 * @mbggenerated
	 */
	private Integer roomSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.bedroom_sum
	 * @mbggenerated
	 */
	private Integer bedroomSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.bed_sum
	 * @mbggenerated
	 */
	private Integer bedSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.toilet_sum
	 * @mbggenerated
	 */
	private Integer toiletSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column house_info.deposit
	 * @mbggenerated
	 */
	private BigDecimal deposit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.house_info_id
	 * @return  the value of house_info.house_info_id
	 * @mbggenerated
	 */
	public String getHouseInfoId() {
		return houseInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.house_info_id
	 * @param houseInfoId  the value for house_info.house_info_id
	 * @mbggenerated
	 */
	public void setHouseInfoId(String houseInfoId) {
		this.houseInfoId = houseInfoId == null ? null : houseInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.landlord_id
	 * @return  the value of house_info.landlord_id
	 * @mbggenerated
	 */
	public String getLandlordId() {
		return landlordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.landlord_id
	 * @param landlordId  the value for house_info.landlord_id
	 * @mbggenerated
	 */
	public void setLandlordId(String landlordId) {
		this.landlordId = landlordId == null ? null : landlordId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.title
	 * @return  the value of house_info.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.title
	 * @param title  the value for house_info.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.province
	 * @return  the value of house_info.province
	 * @mbggenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.province
	 * @param province  the value for house_info.province
	 * @mbggenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.city
	 * @return  the value of house_info.city
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.city
	 * @param city  the value for house_info.city
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.price
	 * @return  the value of house_info.price
	 * @mbggenerated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.price
	 * @param price  the value for house_info.price
	 * @mbggenerated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.district
	 * @return  the value of house_info.district
	 * @mbggenerated
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.district
	 * @param district  the value for house_info.district
	 * @mbggenerated
	 */
	public void setDistrict(String district) {
		this.district = district == null ? null : district.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.address
	 * @return  the value of house_info.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.address
	 * @param address  the value for house_info.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.longitude
	 * @return  the value of house_info.longitude
	 * @mbggenerated
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.longitude
	 * @param longitude  the value for house_info.longitude
	 * @mbggenerated
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.latitude
	 * @return  the value of house_info.latitude
	 * @mbggenerated
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.latitude
	 * @param latitude  the value for house_info.latitude
	 * @mbggenerated
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.signature_url
	 * @return  the value of house_info.signature_url
	 * @mbggenerated
	 */
	public String getSignatureUrl() {
		return signatureUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.signature_url
	 * @param signatureUrl  the value for house_info.signature_url
	 * @mbggenerated
	 */
	public void setSignatureUrl(String signatureUrl) {
		this.signatureUrl = signatureUrl == null ? null : signatureUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.img_url
	 * @return  the value of house_info.img_url
	 * @mbggenerated
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.img_url
	 * @param imgUrl  the value for house_info.img_url
	 * @mbggenerated
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.predict_sum
	 * @return  the value of house_info.predict_sum
	 * @mbggenerated
	 */
	public Integer getPredictSum() {
		return predictSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.predict_sum
	 * @param predictSum  the value for house_info.predict_sum
	 * @mbggenerated
	 */
	public void setPredictSum(Integer predictSum) {
		this.predictSum = predictSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.is_hot_house
	 * @return  the value of house_info.is_hot_house
	 * @mbggenerated
	 */
	public String getIsHotHouse() {
		return isHotHouse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.is_hot_house
	 * @param isHotHouse  the value for house_info.is_hot_house
	 * @mbggenerated
	 */
	public void setIsHotHouse(String isHotHouse) {
		this.isHotHouse = isHotHouse == null ? null : isHotHouse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.creater
	 * @return  the value of house_info.creater
	 * @mbggenerated
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.creater
	 * @param creater  the value for house_info.creater
	 * @mbggenerated
	 */
	public void setCreater(String creater) {
		this.creater = creater == null ? null : creater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.create_time
	 * @return  the value of house_info.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.create_time
	 * @param createTime  the value for house_info.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.modify_user
	 * @return  the value of house_info.modify_user
	 * @mbggenerated
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.modify_user
	 * @param modifyUser  the value for house_info.modify_user
	 * @mbggenerated
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser == null ? null : modifyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.modify_time
	 * @return  the value of house_info.modify_time
	 * @mbggenerated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.modify_time
	 * @param modifyTime  the value for house_info.modify_time
	 * @mbggenerated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.house_type
	 * @return  the value of house_info.house_type
	 * @mbggenerated
	 */
	public String getHouseType() {
		return houseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.house_type
	 * @param houseType  the value for house_info.house_type
	 * @mbggenerated
	 */
	public void setHouseType(String houseType) {
		this.houseType = houseType == null ? null : houseType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.house_describe
	 * @return  the value of house_info.house_describe
	 * @mbggenerated
	 */
	public String getHouseDescribe() {
		return houseDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.house_describe
	 * @param houseDescribe  the value for house_info.house_describe
	 * @mbggenerated
	 */
	public void setHouseDescribe(String houseDescribe) {
		this.houseDescribe = houseDescribe == null ? null : houseDescribe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.grade
	 * @return  the value of house_info.grade
	 * @mbggenerated
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.grade
	 * @param grade  the value for house_info.grade
	 * @mbggenerated
	 */
	public void setGrade(String grade) {
		this.grade = grade == null ? null : grade.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.room_sum
	 * @return  the value of house_info.room_sum
	 * @mbggenerated
	 */
	public Integer getRoomSum() {
		return roomSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.room_sum
	 * @param roomSum  the value for house_info.room_sum
	 * @mbggenerated
	 */
	public void setRoomSum(Integer roomSum) {
		this.roomSum = roomSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.bedroom_sum
	 * @return  the value of house_info.bedroom_sum
	 * @mbggenerated
	 */
	public Integer getBedroomSum() {
		return bedroomSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.bedroom_sum
	 * @param bedroomSum  the value for house_info.bedroom_sum
	 * @mbggenerated
	 */
	public void setBedroomSum(Integer bedroomSum) {
		this.bedroomSum = bedroomSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.bed_sum
	 * @return  the value of house_info.bed_sum
	 * @mbggenerated
	 */
	public Integer getBedSum() {
		return bedSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.bed_sum
	 * @param bedSum  the value for house_info.bed_sum
	 * @mbggenerated
	 */
	public void setBedSum(Integer bedSum) {
		this.bedSum = bedSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.toilet_sum
	 * @return  the value of house_info.toilet_sum
	 * @mbggenerated
	 */
	public Integer getToiletSum() {
		return toiletSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.toilet_sum
	 * @param toiletSum  the value for house_info.toilet_sum
	 * @mbggenerated
	 */
	public void setToiletSum(Integer toiletSum) {
		this.toiletSum = toiletSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column house_info.deposit
	 * @return  the value of house_info.deposit
	 * @mbggenerated
	 */
	public BigDecimal getDeposit() {
		return deposit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column house_info.deposit
	 * @param deposit  the value for house_info.deposit
	 * @mbggenerated
	 */
	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

	@Override
	public String toString() {
		return "HouseInfo [houseInfoId=" + houseInfoId + ", landlordId=" + landlordId + ", title=" + title
				+ ", province=" + province + ", city=" + city + ", price=" + price + ", district=" + district
				+ ", address=" + address + ", longitude=" + longitude + ", latitude=" + latitude + ", signatureUrl="
				+ signatureUrl + ", imgUrl=" + imgUrl + ", predictSum=" + predictSum + ", isHotHouse=" + isHotHouse
				+ ", creater=" + creater + ", createTime=" + createTime + ", modifyUser=" + modifyUser + ", modifyTime="
				+ modifyTime + ", houseType=" + houseType + ", houseDescribe=" + houseDescribe + ", grade=" + grade
				+ ", roomSum=" + roomSum + ", bedroomSum=" + bedroomSum + ", bedSum=" + bedSum + ", toiletSum="
				+ toiletSum + "]";
	}
    
    
    
    
    
}