package cn.amy.product.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import cn.amy.product.web.DateJsonTypeConvert;

public class PriceCalendar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.house_info_id
     *
     * @mbggenerated
     */
    private String houseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.date_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date dateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.room_num
     *
     * @mbggenerated
     */
    private Integer roomNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.month
     *
     * @mbggenerated
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price_calendar.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.id
     *
     * @return the value of price_calendar.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.id
     *
     * @param id the value for price_calendar.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.house_info_id
     *
     * @return the value of price_calendar.house_info_id
     *
     * @mbggenerated
     */
    public String getHouseInfoId() {
        return houseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.house_info_id
     *
     * @param houseInfoId the value for price_calendar.house_info_id
     *
     * @mbggenerated
     */
    public void setHouseInfoId(String houseInfoId) {
        this.houseInfoId = houseInfoId == null ? null : houseInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.date_time
     *
     * @return the value of price_calendar.date_time
     *
     * @mbggenerated
     */
    @JsonSerialize(using=DateJsonTypeConvert.class)
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.date_time
     *
     * @param dateTime the value for price_calendar.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.price
     *
     * @return the value of price_calendar.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.price
     *
     * @param price the value for price_calendar.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.room_num
     *
     * @return the value of price_calendar.room_num
     *
     * @mbggenerated
     */
    public Integer getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.room_num
     *
     * @param roomNum the value for price_calendar.room_num
     *
     * @mbggenerated
     */
    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.month
     *
     * @return the value of price_calendar.month
     *
     * @mbggenerated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.month
     *
     * @param month the value for price_calendar.month
     *
     * @mbggenerated
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price_calendar.status
     *
     * @return the value of price_calendar.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price_calendar.status
     *
     * @param status the value for price_calendar.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    
    
    
    public Date startTime;
    
    public Date endTime;

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Override
	public String toString() {
		return "PriceCalendar [id=" + id + ", houseInfoId=" + houseInfoId + ", dateTime=" + dateTime + ", price="
				+ price + ", roomNum=" + roomNum + ", month=" + month + ", status=" + status + ", startTime="
				+ startTime + ", endTime=" + endTime + "]";
	}
	
}